git clone https://gitee.com/mirrors/ArangoDB
git clone https://gitee.com/mirrors/avs-device-sdk
git clone https://gitee.com/mirrors/aws-sdk-java
git clone https://gitee.com/mirrors/CAS
git clone https://gitee.com/mirrors/cinder
git clone https://gitee.com/mirrors/client_java
git clone https://gitee.com/mirrors/compose
git clone https://gitee.com/mirrors/core-plot
git clone https://gitee.com/mirrors/cups
git clone https://gitee.com/mirrors/cxf
git clone https://gitee.com/mirrors/data-science-ipython-notebooks
git clone https://gitee.com/mirrors/deck.gl
git clone https://gitee.com/mirrors/dhcpcd
git clone https://gitee.com/mirrors/django-celery-results
git clone https://gitee.com/mirrors/elasticsearch-analysis-pinyin
git clone https://gitee.com/mirrors/elasticsearch-hadoop
git clone https://gitee.com/mirrors/electron
git clone https://gitee.com/mirrors/elixir
git clone https://gitee.com/mirrors/ember.js
git clone https://gitee.com/mirrors/emotion
git clone https://gitee.com/mirrors/emqx
git clone https://gitee.com/mirrors/EntityFramework6
git clone https://gitee.com/mirrors/error-prone
git clone https://gitee.com/mirrors/ESLint
git clone https://gitee.com/mirrors/etcd
git clone https://gitee.com/mirrors/fastdfs
git clone https://gitee.com/mirrors/Fastify
git clone https://gitee.com/mirrors/Firefox-iOS
git clone https://gitee.com/mirrors/flask
git clone https://gitee.com/mirrors/flink
git clone https://gitee.com/mirrors/flowable-engine
git clone https://gitee.com/mirrors/gcc
git clone https://gitee.com/mirrors/gradle
git clone https://gitee.com/mirrors/intellij-community
git clone https://gitee.com/mirrors/kibana
git clone https://gitee.com/mirrors/kotlin
git clone https://gitee.com/mirrors/linaro_toolchains_2014
git clone https://gitee.com/mirrors/linux
git clone https://gitee.com/mirrors/MixedRealityToolkit-Unity
git clone https://gitee.com/mirrors/mptcp
git clone https://gitee.com/mirrors/noto-cjk
git clone https://gitee.com/mirrors/noto-fonts
git clone https://gitee.com/mirrors/open-source-rover
git clone https://gitee.com/mirrors/percona-server
