git clone https://gitee.com/mirrors/percona-xtrabackup
git clone https://gitee.com/mirrors/platform_frameworks_base
git clone https://gitee.com/mirrors/platform_packages_apps_settings
git clone https://gitee.com/mirrors/PTP
git clone https://gitee.com/mirrors/puttyclip
git clone https://gitee.com/mirrors/pytorch
git clone https://gitee.com/mirrors/qTip2
git clone https://gitee.com/mirrors/siproxd_orange
git clone https://gitee.com/mirrors/sisu-guice
git clone https://gitee.com/mirrors/sjcl
git clone https://gitee.com/mirrors/skydive
git clone https://gitee.com/mirrors/skyfactory-2.4-faults
git clone https://gitee.com/mirrors/slack-sql
git clone https://gitee.com/mirrors/slick
git clone https://gitee.com/mirrors/SlickGrid
git clone https://gitee.com/mirrors/slick-pg
git clone https://gitee.com/mirrors/Sloth
git clone https://gitee.com/mirrors/slp-sharp
git clone https://gitee.com/mirrors/smarthome
git clone https://gitee.com/mirrors/smart_open
git clone https://gitee.com/mirrors/smarty
git clone https://gitee.com/mirrors/smile
git clone https://gitee.com/mirrors/smn-sdk-go
git clone https://gitee.com/mirrors/smn-sdk-java2.0
git clone https://gitee.com/mirrors/smooks
git clone https://gitee.com/mirrors/smp_utils
git clone https://gitee.com/mirrors/SnapKit
git clone https://gitee.com/mirrors/Snappy
git clone https://gitee.com/mirrors/snappy-java
git clone https://gitee.com/mirrors/snaptree
git clone https://gitee.com/mirrors/snmp-blog
git clone https://gitee.com/mirrors/snmpman
git clone https://gitee.com/mirrors/snort3
git clone https://gitee.com/mirrors/snowflake
git clone https://gitee.com/mirrors/soap-ws
git clone https://gitee.com/mirrors/socialmanagertools-igbot
git clone https://gitee.com/mirrors/social_mapper
git clone https://gitee.com/mirrors/socket.io
git clone https://gitee.com/mirrors/socket.io-client
git clone https://gitee.com/mirrors/SocketIoClientDotNet
git clone https://gitee.com/mirrors/socket.io-client-swift
git clone https://gitee.com/mirrors/SocketRocket
git clone https://gitee.com/mirrors/sockjs-client
git clone https://gitee.com/mirrors/sodium_compat
git clone https://gitee.com/mirrors/software-o-o
git clone https://gitee.com/mirrors/solaris-openssl-fips
git clone https://gitee.com/mirrors/solidrun-linaro-linux.3.14
git clone https://gitee.com/mirrors/SoLoader
git clone https://gitee.com/mirrors/sonarqube
git clone https://gitee.com/mirrors/sorl-thumbnail
git clone https://gitee.com/mirrors/Sortable
git clone https://gitee.com/mirrors/sosreport
git clone https://gitee.com/mirrors/Soundflower
git clone https://gitee.com/mirrors/SoundJS
git clone https://gitee.com/mirrors/SoundManager2
git clone https://gitee.com/mirrors/soupsieve
git clone https://gitee.com/mirrors/sourceforge-jexcelapi
git clone https://gitee.com/mirrors/sourcemap
git clone https://gitee.com/mirrors/spacefn-evdev
git clone https://gitee.com/mirrors/spark
git clone https://gitee.com/mirrors/spark-csv
git clone https://gitee.com/mirrors/spark-dependencies
git clone https://gitee.com/mirrors/spark-ec2
git clone https://gitee.com/mirrors/sparkling-water
git clone https://gitee.com/mirrors/spark-timeseries
git clone https://gitee.com/mirrors/spark-transformers
git clone https://gitee.com/mirrors/sparsepp
git clone https://gitee.com/mirrors/spatial-framework-for-hadoop
git clone https://gitee.com/mirrors/spdk
git clone https://gitee.com/mirrors/spdystream
git clone https://gitee.com/mirrors/speakeasy
git clone https://gitee.com/mirrors/spec
git clone https://gitee.com/mirrors/specification
git clone https://gitee.com/mirrors/spectator
git clone https://gitee.com/mirrors/spectrum
git clone https://gitee.com/mirrors/speech-synth
git clone https://gitee.com/mirrors/sphinx_rtd_theme
git clone https://gitee.com/mirrors/spiffs
git clone https://gitee.com/mirrors/spin.js
git clone https://gitee.com/mirrors/spire
git clone https://gitee.com/mirrors/SPIRV-Cross
git clone https://gitee.com/mirrors/spongycastle
git clone https://gitee.com/mirrors/spprocpool
git clone https://gitee.com/mirrors/spray-json
git clone https://gitee.com/mirrors/sprig
git clone https://gitee.com/mirrors/spring
git clone https://gitee.com/mirrors/SpringAll
git clone https://gitee.com/mirrors/spring-amqp
git clone https://gitee.com/mirrors/spring-batch
git clone https://gitee.com/mirrors/spring-boot
git clone https://gitee.com/mirrors/spring-boot-admin
git clone https://gitee.com/mirrors/spring-boot-all
git clone https://gitee.com/mirrors/springboot-angular-atmosphere-quickstart
git clone https://gitee.com/mirrors/spring-boot-demo
git clone https://gitee.com/mirrors/springboot-learn
git clone https://gitee.com/mirrors/spring-boot-starter-swagger
git clone https://gitee.com/mirrors/spring-cloud-aws
git clone https://gitee.com/mirrors/spring-cloud-bus
git clone https://gitee.com/mirrors/spring-cloud-cloudfoundry
git clone https://gitee.com/mirrors/spring-cloud-commons
git clone https://gitee.com/mirrors/spring-cloud-config
git clone https://gitee.com/mirrors/spring-cloud-consul
git clone https://gitee.com/mirrors/spring-cloud-contract
git clone https://gitee.com/mirrors/Spring-Cloud-Function
git clone https://gitee.com/mirrors/spring-cloud-gateway
git clone https://gitee.com/mirrors/spring-cloud-gcp
git clone https://gitee.com/mirrors/spring-cloud-kubernetes
git clone https://gitee.com/mirrors/spring-cloud-netflix
